name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

# Grant GITHUB_TOKEN the necessary permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # Add these lines to your deployment job
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0' # Use a stable Node version

      # Build and deploy using the community action
      - name: Deploy Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static # The directory where your storybook is built
          build_command: npm run build-storybook # Your build command
